[project]
name = "python-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "stevecyj", email = "ycsteven.tsao@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.6.2",
    "notebook>=7.6.1",
    "pandas>=3.0.5",
]

[project.scripts]
python-course = "python_course:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
