[project]
name = "hw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "stevecyj", email = "ycsteven.tsao@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "notebook>=7.6.2",
    "requests>=2.34.2",
]

[project.scripts]
hw = "hw:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
